### ISSUE TITLE
Incorrect default template for bytes type

### ISSUE THREAD

**Issue by shaneqld** [bloomrpc/bloomrpc#101]
When using the `bytes` type, the default template that the editor creates is incorrect and does not correctly serialize.

With the example message,

```proto
message Policy {
  bytes etag = 2;
}
```

the editor creates the template:

```json
{
  "etag": {
    "type": "Buffer",
    "data": [
      164,
      178,
      11,
      40
    ]
  }
}
```

When used in a request, this does not correctly serialize and results in an empty/omitted `etag` being sent.

If you change the request such as so:

```json
{
  "etag": [ 1, 2, 3, 4 ]
}
```

or as so:

```json
{
  "etag": "YWJjMTIzIT8kKiYoKSctPUB+"
}
```

then it is correctly serialized.

The latter example is a base64 encoded string.  As specified in the [Language Guide (proto3)](https://developers.google.com/protocol-buffers/docs/proto3#json), the `bytes` type should be encoded as a base64 string in JSON.

As such, may I suggest changing the default template to use a base64 encoded string for the `bytes` type. :)

**Comment by fenos** [comment]
@shaneqld Hi, Thanks for the very detailed issue, much appreciated!

This is interesting, I'll be trying this out and release a fix for the coming release!

**Comment by VictorMonte** [comment]
Hi guys,

I have the same problem as @shaneqld.
Although, even if I change the request as @shaneqld commented, the parse still doesn't happen.
If you need any help, just let me know.

**Comment by jadwahab** [comment]
Hey guys, we have the same issue. Just to follow up on @shaneqld 's point, if you are going to support byte encoding to string, I would suggest encoding as hex instead of base64 in order to make it more readable and compatible with other things like bitcoin for example. Cheers!

**Comment by shaneqld** [comment]
> Hey guys, we have the same issue. Just to follow up on @shaneqld 's point, if you are going to support byte encoding to string, I would suggest encoding as hex instead of base64 in order to make it more readable and compatible with other things like bitcoin for example. Cheers!

JSON mapping should follow [Proto3 Language Guide](https://developers.google.com/protocol-buffers/docs/proto3#json), which specifies base64 for the bytes type. I don’t think it would be wise to deviate from the standard.

**Comment by ptadros** [comment]
I still have the same issue in version "Version 1.4.1 (1.4.1.145)". Any update about it? Thank you

**Comment by StarToLeft** [comment]
Still an issue in Version 1.5.2

**Comment by muusbolla** [comment]
It seems according to the comments on https://github.com/uw-labs/bloomrpc/issues/29 that it is intended to correctly serialize, but it doesn't work. I also cannot read the sent value on a Go server.

I'd like to additionally request that when fixing the issue so that the Buffer type serializes correctly, that you support input formatting in the same way as metadata - https://github.com/uw-labs/bloomrpc/pull/123

The reason for this is here: https://stackoverflow.com/questions/66378163/grpc-test-client-gui-that-supports-representing-a-bytes-type-as-a-hex-string I want to be able to put a hex string "6000e9720C683f1b8e638a49" and have that be interpreted as a byte array instead of having to manually convert and enter [96,0,233,114,12,104,63,27,142,99,138,73]. I believe that the formatting logic that already exists for the metadata Buffer would enable this.

**Comment by quesurifn** [comment]
Still an issue.

**Comment by cpatchett-iqbo** [comment]
Lots of complaints on this issue, no offers to help fix.

**Comment by andream16** [comment]
Having the same issue.

**Comment by cgfarmer4** [comment]
🤦

**Comment by matiasinsaurralde** [comment]
I'm facing the same issue.

**Comment by eeyrw** [comment]
Still an issue in 1.5.3.

**Comment by andream16** [comment]
Got a fix for it https://github.com/uw-labs/bloomrpc-mock/pull/23 but has never been reviewed

**Comment by jduan-highnote** [comment]
I was baffled why my service was getting empty data for "bytes" fields until I found this issue. The suggestion worked beautifully.

**Comment by karol-bisztyga** [comment]
`1.5.3` still suffering from this, bump!
