### ISSUE TITLE
Bloomrpc behind https proxy

### ISSUE THREAD

**Issue by arosetti** [bloomrpc/bloomrpc#385]
Hello, I'm having troubles using with Bloomrpc behind an nginx proxy.

I have a kubernetes deployment with an ingress controller that uses the nginx proxy to expose some grpc api (for bidirectional streaming) but also other rest+swagger apis.

The URL for the grpc service is something like https://website.com/service.

I've tried using the Kreya grpc client and it works but that client has problems with the interactive mode in the bidirectional streaming.

this is the error:
`
{
  "error": "14 UNAVAILABLE: DNS resolution failed"
}
`

**Comment by manuelnagler** [comment]
I also noticed BloomRpc does not like TLS connections. However, your error + description tell me that you typed
"https://" in front of the url -> that is not how it works -> just start with your hostname
Also dont add any /service afterwards -> grpc cannot be on a subpath. You always have to use the root path

The only thing you can add is a port, e.g. example.com:9090

However Bloomrpm + TLS still results in
{
  "error": "14 UNAVAILABLE: failed to connect to all addresses"
}
Since my application works with TLS and also Kreya works I assume its a BloomRpc issue
