### ISSUE TITLE
[Feature Request] Simple macros or pre-defined variables such as timestamp etc.

### ISSUE THREAD

**Issue by vivekragunathan** [bloomrpc/bloomrpc#75]
It would be handy if BloomRPC provides at least pre-defined variables or macros, if not custom defined ones, such as timestamp, random string/number etc. that can be used in the GRPC request body (message).

**Comment by fenos** [comment]
Hi @VivekRagunathan thanks for the feature request it looks very handy from the sound of it.

Could give me an example on how you'd like to define and use those macro within the editor?

**Comment by VivekRagunathan** [comment]
Hi @fenos This feature would be very handy when you would like pass distinct values each time in the request. Some of the reasons where this macro would be very helpful:

- One of the main reasons for such thing is to make sure you are working off of cached responses. 
- Say when the server processes a request and insert some values in the DB and you want to use the API to do the insertion rather than directly adding values to the DB (and you need distinct values each time).
- Generally, you don't want to switch to command line or a tool that generates these random values or timestamps, copy and paste it here in BloomRPC. It would be handy to do in BloomRPC itself.

The value I imagine I would use is something along these lines ... Ignore the details of naming and syntax.

```
{
  "person": {
    "name": "John",
    "registeredTimestamp": ${dateTime.beforeDays(10)},
    "lastLoginTime": ${dateTime.now()},
  },
  "msg": {
    "value": ${randomAlphaString}
  }
}
```

Let me know if that helps.

**Comment by fenos** [comment]
Hi @VivekRagunathan thanks for the example!

I think this is a kind of evolution of https://github.com/uw-labs/bloomrpc/issues/6 which will allow the editor to use variables within the request.

Since we are in the javascript world we could have functions as named variables!


I do think that request variables should be the logical step forward to enable this feature.
I also think **request variables** should be the next big feature release on `BloomRPC` (coming soon)
